version: '3.8'

services:
  # Service cho Laravel (PHP + Composer)
  app:
    build:
      context: ./docker/php
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - app_network

  # Service cho MySQL
  db:
    image: mysql:8
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app_network

  # Service cho Nginx
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

  # Service cho Vue.js (Node.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    restart: unless-stopped
    networks:
      - app_network
  nginx_frontend:
    image: nginx:latest
    container_name: vue_nginx
    restart: unless-stopped
    ports:
      - "8080:80"  # Chạy frontend trên cổng 8080
    volumes:
      - ./docker/nginx/frontend.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html  # Chạy Vue từ thư mục này
      - ./docker/nginx/.htpasswd:/etc/nginx/.htpasswd  # Basic Auth
    depends_on:
      - frontend
    networks:
      - app_network
  
  # Service cho phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"  # phpMyAdmin sẽ chạy trên http://localhost:8081
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  dbdata:
